AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Getcontacts:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::177285995440:role/service-role/Get_contacts-role-fmacqxp4'
      Layers:
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Beautifulsoup:1'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Phonenumbers:1'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Tldextract:1'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Pandas_Numpy:1'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Getcontacts_others:5'
