AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ParentAPIFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 30
      Role: >-
        arn:aws:iam::177285995440:role/service-role/ParentAPIFunction-role-ry20chpc
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Pandas:3'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Numpy:1'
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:Sagemaker:8'
