AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CompanyAutocomplete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 120
      Role: >-
        arn:aws:iam::177285995440:role/service-role/CompanyAutocomplete-role-b5zs2l7n
      Layers:
        - 'arn:aws:lambda:eu-west-3:177285995440:layer:CompanyAutocompleteLayer:1'
